# This will be a toml version of the US income tax return form 1040

Filing_Status = "Married filing jointly"
FN_MI = "Ketan C"
LN = "Maheshwari"

[Address]
    Street = "743 Park Ave"
    Apt_no = 14
    City = "Detroit"
    State = "Michigan"
    Zip = 12345
    Foreign_country = ""
    Foreign_State = ""
    Foreign_postal = ""

Your_ssn = "334-22-5678"
Spouse_ssn = "456-78-1990"

Pres_Ele_Camp = "none"

Virtual_Currency = "No"

[Standard_Deduction]
    claim_you_as_dep = "No"
    claim_spouse_as_dep = "No"
    alien_or_sep_return = "No"
    
[Age_blindness]
    born_before_Jan2_1956 = "No"
    blind = "No"
    spouse_born_before_Jan2_1956 = "No"
    Spouse_blind = "No"

[Dependents]
    [Dep1]
        FN_LN = "Robert Jones"
        Ssn = "356-22-7856"
        Rel = "son"
        Child_tax_cred = "Yes"
        Cred_for_other_deps = "No"
    [Dep2]
        FN_LN =	"Mary Jones"
       	Ssn = "326-25-1856"
       	Rel = "daughter"
       	Child_tax_cred = "Yes"
       	Cred_for_other_deps = "No"
    [Dep3]
        FN_LN =	""
       	Ssn = ""
       	Rel = ""
       	Child_tax_cred = "" 
       	Cred_for_other_deps = ""
    [Dep4]
        FN_LN =	""
       	Ssn = ""
       	Rel = ""
       	Child_tax_cred = ""
       	Cred_for_other_deps = "" 
    
    more_than_4_deps = "No"

# i = item

[Main]
    i_1 = 0
    i_2a = 0
    i_2b = 0
    i_3a = 0
    i_3b = 0
    i_4a = 0
    i_4b = 0
    i_5a = 0
    i_5b = 0
    i_6a = 0
    i_6b = 0
    i_7 = 0
    i_8 = 0
    i_9 = 0
    i_10a = 0
    i_10b = 0
    i_10c = 0
    i_11 = 0
    i_12 = 0
    i_13 = 0
    i_14 = 0
    i_15 = 0
    i_16 = 0
    i_17 = 0
    i_18 = 0
    i_19 = 0
    i_20 = 0
    i_21 = 0
    i_22 = 0
    i_23 = 0
    i_24 = 0
    i_25a = 0
    i_25b = 0
    i_25c = 0
    i_25d = 0
    i_26 = 0
    i_27 = 0
    i_28 = 0
    i_29 = 0
    i_30 = 0
    i_31 = 0
    i_32 = 0
    i_33 = 0

[Refund]

[Amount_you_owe]

[Third_party_designee]

[Signature]

[Paid_preparer]

